/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadg23.vistas;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import universidadg23.accesoADatos.AlumnoData;
import universidadg23.accesoADatos.InscripcionData;
import universidadg23.accesoADatos.MateriaData;
import universidadg23.accesoADatos.Validaciones;
import universidadg23.entidades.Alumno;
import universidadg23.entidades.Inscripcion;
import universidadg23.entidades.Materia;

/**
 *
 * @author pmora
 */
public class FormularioCargadeNotasView extends javax.swing.JInternalFrame {

    FondoPanel fondo = new FondoPanel();
    private Alumno alumno;
    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    private DefaultComboBoxModel comboModel = new DefaultComboBoxModel() {
    };

    public FormularioCargadeNotasView() {
        this.setContentPane(fondo);
        initComponents();
        armarCabecera();
        jtNombreMateria.setEnabled(false);
        jtNota.setEnabled(false);
        jBGuardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMateria = new javax.swing.JTable();
        jBGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtNombreMateria = new javax.swing.JTextField();
        jtNota = new javax.swing.JTextField();
        jtDNI = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jlAlumno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Carga de Notas");

        jLabel2.setText("DNI");

        jTMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTMateriaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTMateria);

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione una materia para cargar la nota");

        jLabel4.setText("Materia");

        jLabel5.setText("Nota");

        jtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtDNIKeyReleased(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jlAlumno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlAlumno.setForeground(new java.awt.Color(0, 51, 102));

        jLabel6.setText("Alumno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jBGuardar)
                        .addGap(227, 227, 227)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jlAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jButton2))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Al presionar el boton jbSalida se cierra el JInternar frame de Formulario
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        try {
            AlumnoData alumData = new AlumnoData();
            alumno = alumData.buscarAlumnoPorDni(Integer.valueOf(jtDNI.getText()));
            if (alumno != null) {
                tableClean();
                jlAlumno.setText(alumno.getApellido() + ", " + alumno.getNombre());
                InscripcionData inscDat = new InscripcionData();
                List<Inscripcion> inscripcion = new ArrayList<>();
                inscripcion = inscDat.listarInscripcionesPorAlumno(alumno.getIdAlumno());
                for (Inscripcion inscpto : inscripcion) {
                    modelo.addRow(new Object[]{inscpto.getMateria().getIdMateria(), inscpto.getMateria().getNombre(), inscpto.getNota()});
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "No se permiten campos vacios y/o caracter invalidos");
        }


    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTMateriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMateriaMouseReleased

        jtNota.setEnabled(true);
        jtNota.setText(modelo.getValueAt(jTMateria.getSelectedRow(), 2).toString());
        jtNombreMateria.setText(modelo.getValueAt(jTMateria.getSelectedRow(), 1).toString());
        jBGuardar.setEnabled(true);

    }//GEN-LAST:event_jTMateriaMouseReleased

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed

        try {
            double nota = Double.parseDouble(jtNota.getText());
            nota = (int) (nota * 10);
            nota = nota / 10;
            InscripcionData inscData = new InscripcionData();
            if (nota >= 0 && nota <= 10) {
                inscData.actualizarNota(alumno.getIdAlumno(), (int) (modelo.getValueAt(jTMateria.getSelectedRow(), 0)), nota);
                jBBuscarActionPerformed(evt);
                jtNota.setEnabled(false);
                jBGuardar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "La nota ingresada debe ser entre 0 y 10");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "No se permiten campos vacios y/o caracter invalidos");
        }


    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jtDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDNIKeyReleased
        if (!jtDNI.getText().equals("") && Validaciones.validacionInmediataCaracteres(jtDNI.getText(), 1) == false) {
            JOptionPane.showMessageDialog(this, "Solo se permiten numeros");
            jtDNI.setText("");
        }
    }//GEN-LAST:event_jtDNIKeyReleased

    private void armarCabecera() {

        modelo.addColumn("CODIGO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("NOTA");
        jTMateria.setModel(modelo);

    }

    private void tableClean() {
        //Realiza el chequeo de que la JTMaterias este vacia y si no lo esta la limpia
        if (jTMateria.getRowCount() != 0) {
            int largo = jTMateria.getRowCount() - 1;
            for (; largo >= 0; largo--) {
                modelo.removeRow(largo);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTMateria;
    private javax.swing.JLabel jlAlumno;
    private javax.swing.JTextField jtDNI;
    private javax.swing.JTextField jtNombreMateria;
    private javax.swing.JTextField jtNota;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/universidadg23/vistas/Imagenes/LogoULP.png")).getImage();
            g.drawImage(imagen, 0, 0, 100, 39, this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
