/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadg23.vistas;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jonac
 */
public class jfMenuPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form jfMenuPrincipal
     */
    public jfMenuPrincipal() {
        initComponents();
        setSize(800,607);
        setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jdEscritorio = new javax.swing.JDesktopPane();
        jlFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmFormularioAlumno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiFormularioMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiFormularioInscripciones = new javax.swing.JMenuItem();
        jmiFormularioCargaNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMAlumnosXMateria = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de gestion Universidad de la Punta");
        setIconImage( Toolkit.getDefaultToolkit().getImage(getClass().getResource("/universidadg23/vistas/Imagenes/IconoGrande.png")));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jdEscritorio.setMinimumSize(new java.awt.Dimension(400, 0));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadg23/vistas/Imagenes/Fondo.jpg"))); // NOI18N

        jdEscritorio.setLayer(jlFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdEscritorioLayout = new javax.swing.GroupLayout(jdEscritorio);
        jdEscritorio.setLayout(jdEscritorioLayout);
        jdEscritorioLayout.setHorizontalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdEscritorioLayout.createSequentialGroup()
                .addComponent(jlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jdEscritorioLayout.setVerticalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jlFondo.getAccessibleContext().setAccessibleParent(jlFondo);

        jMenu1.setText("Alumno");

        jmFormularioAlumno.setText("Formulario Alumnos");
        jmFormularioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormularioAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(jmFormularioAlumno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materia");

        jmiFormularioMateria.setText("Formulario Materias");
        jmiFormularioMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiFormularioMateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administracion");

        jmiFormularioInscripciones.setText("Formulario Inscripciones");
        jmiFormularioInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioInscripcionesActionPerformed(evt);
            }
        });
        jMenu3.add(jmiFormularioInscripciones);

        jmiFormularioCargaNotas.setText("Carga de notas");
        jmiFormularioCargaNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioCargaNotasActionPerformed(evt);
            }
        });
        jMenu3.add(jmiFormularioCargaNotas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        jMAlumnosXMateria.setText("Alumnos por Materia");
        jMAlumnosXMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAlumnosXMateriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMAlumnosXMateria);

        jMenuBar1.add(jMenu4);

        jmSalir.setText("Opciones");

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmSalir.add(jmiSalir);

        jMenuItem3.setText("Sobre...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmSalir.add(jMenuItem3);

        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEscritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmFormularioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormularioAlumnoActionPerformed
        // Al presionar el miFormulario abre el JPanel Formulario
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        FormularioAlumnoView fav = new FormularioAlumnoView();
        centrarFrame(fav);
        agregarFondoVentana(fav);
    }//GEN-LAST:event_jmFormularioAlumnoActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // Al presionar el Menu Salida se cierra el Jframe MenuPrincipal
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiFormularioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioMateriaActionPerformed
        // Al presionar el MIFormulario Materias abre el JPanel FormularioMateriaView
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        FormularioMateriaView fmv = new FormularioMateriaView();
        centrarFrame(fmv);
        agregarFondoVentana(fmv);
    }//GEN-LAST:event_jmiFormularioMateriaActionPerformed

    private void jmiFormularioInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioInscripcionesActionPerformed
        // Al presionar el MIFormulario Inscripciones abre el JPanel FormularioInscripcionView
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        FormularioInscripcionView fiv = new FormularioInscripcionView();
        centrarFrame(fiv);  
        agregarFondoVentana(fiv);
    }//GEN-LAST:event_jmiFormularioInscripcionesActionPerformed

    private void jmiFormularioCargaNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioCargaNotasActionPerformed
        // Al presionar el MIFormulario Inscripciones abre el JPanel FormularioCargadeNotasView
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        FormularioCargadeNotasView fcnv = new FormularioCargadeNotasView();
        centrarFrame(fcnv);
        agregarFondoVentana(fcnv);
    }//GEN-LAST:event_jmiFormularioCargaNotasActionPerformed

    private void jMAlumnosXMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAlumnosXMateriaActionPerformed
        // al presionar el jMenuItem [consulta x materia] abre el jInternalFrame formulario consulta alumno por materia 
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        FormularioConsultaAlumnoXMateria fcam = new FormularioConsultaAlumnoXMateria();
        centrarFrame(fcam);
        agregarFondoVentana(fcam);
    }//GEN-LAST:event_jMAlumnosXMateriaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Sobre el producto
        JOptionPane.showMessageDialog(null, "Proyecto Transversal para la Universidad de la Punta\n\nGrupo 23:\nCabral Lucas\nCarabetta Jonathan\nJuárez Angel\nPerez Mauro\n\n© 2023 Universidad de la Punta");
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMenuPrincipal().setVisible(true);
            }
        });
    }
    
    private void centrarFrame(JInternalFrame form){
        Dimension desktopSize = jdEscritorio.getSize();
        int x = (desktopSize.width - form.getWidth()) / 2;
        int y = (desktopSize.height - form.getHeight()) / 2;
        form.setLocation(x, y);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMAlumnosXMateria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JDesktopPane jdEscritorio;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JMenuItem jmFormularioAlumno;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiFormularioCargaNotas;
    private javax.swing.JMenuItem jmiFormularioInscripciones;
    private javax.swing.JMenuItem jmiFormularioMateria;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
    private void agregarFondoVentana (Component fv){
        fv.setVisible(true);
        jdEscritorio.add(fv);
        jdEscritorio.add(jlFondo);
        jdEscritorio.moveToFront(jlFondo);
        jdEscritorio.moveToFront(fv);
    }
    private void Icon(JFrame j){
            Image icon = Toolkit.getDefaultToolkit().getImage("/universidadg23/vistas/Imagenes/LogoULP.png");
            j.setIconImage(icon);
    }
}



